---
title: "COVID19 cases"
author: "LPapaiMD"
date: '2020 04 17 '
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
## -DATA-
library(data.table)
library(magrittr)
library(htmltools)
library(ggplot2)
library(gganimate)
library(plotly)

#FUNCTION: Number formatting and rounding
formatNum<-function(number){
      format(round(as.numeric(number),2),nsmall=1, big.mark = " ")
}
#Replace vectors
rc<-c("cases"="Cases","deaths"="Deaths","ratioDC"="Deaths/Cases ratio","ratioCP"="Cases/1000people ratio")

###################
# Getting the dataset
url <- "https://opendata.ecdc.europa.eu/covid19/casedistribution/csv"
data<-read.csv(url, na.strings = "", fileEncoding = "UTF-8-BOM")

# Converting to data.table
data<-data.table(data)

# specifying date class
data$dateRep<-as.Date(data$dateRep, tryFormats = c("%Y-%m-%d", "%d/%m/%Y"))
setnames(data,"countriesAndTerritories","country")

# Growth Rate time frame
grtu <- 3
setkey(data,dateRep)
# Computing cumulative sums and ratios:
d<-data[,':='(Cumulative.Cases=cumsum(cases),Cumulative.Deaths=cumsum(deaths),
                            pop=popData2018[1]),
        by=country][Cumulative.Cases>10,':='(GrowthRate= (Cumulative.Cases-shift(Cumulative.Cases,n=grtu))/(shift(Cumulative.Cases,n=grtu)-shift(Cumulative.Cases,n=2*grtu)),
                                        Cumulative.RatioDC=100*Cumulative.Deaths/Cumulative.Cases,
                                        Cumulative.RatioCP=1000*Cumulative.Cases/popData2018[1]), 
                    by=country][,':='(countryterritoryCode=NULL,geoId=NULL)]
```

## R Markdown

- Over **2 million** people infected so far.
- Around 140.000 confirmed **deaths**
- 213 affected **countries**
- 80% of cases are **asymptomatic**

## Most cases relative to the population

```{r, echo=T}
mostcases<-d[dateRep==max(dateRep) & Cumulative.Cases>6,][
      order(-Cumulative.Cases),head(.SD,15)][,.(country,Cumulative.Cases,pop,Cumulative.RatioCP)]
mostcases
```


## Countries with exponential growth

```{r, warning=F}
topfive<-d[country %in% mostcases$country,][order(dateRep),]
p<-ggplot(topfive,aes(x=Cumulative.Cases, y=cases, color=country)) +
  geom_point(aes(size=pop)) + 
  geom_text(aes(label=country)) +
  scale_x_continuous(trans='log2')+
  # scale_color_viridis_d()+
  scale_y_continuous(trans='log2')+
  ggtitle("Trajectory of COVID-19 Confirmed Cases") +
  xlab("Cumulative case count") +
  ylab("New case count")+
  transition_time(dateRep)+
  labs(subtitle="Date: {frame_time}") +
  shadow_mark(wake_length = 0.05,alpha=F, size=0.5)
animate(p, fps=15,duration=18)
```

## Deaths - cases plot
```{r, warning=F}
plot_ly(d[dateRep==max(dateRep) & Cumulative.Cases>50,][order(-pop),head(.SD,80)], type = 'scatter', mode = 'markers',
        x=~log(1+Cumulative.RatioCP), y=~log(1+Cumulative.RatioDC), color=~country, size=~pop, hoverinfo='text', 
        sizes = c(10, 70), marker = list(sizemode = 'diameter'),
        text=~paste(country,
                    '<br>Population:',
                    format(pop,big.mark=" "),
                    '<br>Cumulative cases:',
                    format(Cumulative.Cases,big.mark=" "),
                    '<br>Cumulative deaths:',
                    format(Cumulative.Deaths,big.mark=" "))) %>%
      layout(title="relative deaths ~ rel. cases (size=population)",
             xaxis=list(title="Relative case count (log cases/1000 ppl)",showgrid = FALSE),
             yaxis=list(title="Relative death count (log deaths/100 cases)",showgrid = FALSE),
             showLegend=F)
```

